from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time
import pandas as pd


# Expanded dictionary for crops (English to Marathi)
crop_en_to_mr = {
    "fig dry": "अंजीर (सुके)",
    "ambadi leaves": "अंबाडी भाजी",
    "pineapple": "अननस",
    "taro": "अर्वी",
    "avocado": "अवकाडो",
    "pigeon pea": "अटर",
    "tamarind pulp": "आंबट चुक",
    "iceberg lettuce": "आइसबर्ग",
    "ginger": "आले",
    "dry ginger": "आले (सुंठ)",
    "amla": "आवळा",
    "black gram": "उडीद",
    "black gram dal": "उडीद डाळ",
    "sugarcane": "उस",
    "castor": "एरण्डी",
    "curry leaves": "कचिपत्ता",
    "bitter gourd": "करडई",
    "bitter gourd leaves": "करडई (भाजी)",
    "calling": "कॉलिंग",
    "onion": "कांदा",
    "onion leaves": "कांदा पात",
    "cucumber": "काकडी",
    "bottle gourd": "कागडा",
    "cashew": "काजू",
    "bitter gourd fruit": "करली",
    "carnation": "कार्नेशन",
    "raw mango": "कालवड",
    "horse gram": "कुलथी",
    "banana": "केळी",
    "raw banana": "केळी (कच्ची)",
    "papaya": "केरी",
    "ridge gourd": "कोहंबडी",
    "coriander": "कोथिंबिर",
    "cabbage": "कोबी",
    "pumpkin": "कोहळा",
    "tea leaves": "खपरी",
    "melon": "खरबुज",
    "guar": "गवार",
    "wheat": "गहू",
    "carrot": "गाजर",
    "cow": "गाय",
    "rose": "गुलाब",
    "jaggery": "गुळ",
    "mustard": "सरसव",
    "jowar": "ज्वारी",
    "cumin": "जीरे",
    "chickpea": "हरभरा",
    "sugar": "साखर",
    "sago": "साबुदाणा",
    "custard apple": "सिताफळ",
    "betel nut": "सुपारी",
    "yam": "सुरन",
    "banana flower": "सुरफुल",
    "salad": "सॅलड",
    "soybean": "सोयाबीन",
    "beetroot": "बीट",
    "baby corn": "बेबी कॉर्न",
    "brinjal": "बैज",
    "broccoli": "ब्रोकोली",
    "rice": "भात - धान",
    # Add remaining crops here...
}


# Extended English to Marathi dictionary for cities (expand as needed)
city_en_to_mr = {
    "ambad": "अंबड (वडी गोद्री)",
    "akluj": "अकलुज",
    "akot": "अकोट",
    "akola": "अकोला",
    "amravati": "अमरावती",
    "amravati fruit and vegetable": "अमरावती- फळ आणि भाजीपाला",
    "amalner": "अमळनेर",
    "alibag": "अलिबाग",
    "ahmedpur": "अहमहपूर",
    "ahilyanagar": "अहिल्यानगर",
    "ambejobali": "आंबेजोबाई",
    "akhadabalapur": "आखाडाबाळापूर",
    "atpadi": "आटपाडी",
    "amgav": "आमगाव",
    "armeri desaignj": "आरमेरी -देसाइगंज",
    "armori": "आरमोरी",
    "arni": "आर्णी",
    "shevgaon": "शेवगाव",
    "shevgaon bhodegav": "शेवगाव - भोदेगाव",
    "shrigonda": "श्रीगोंदा",
    "shrirampur": "श्रीरामपूर",
    "sangamner": "संगमनेर",
    "satana": "सटाणा",
    "sangli": "सांगली",
    "sangli fruits and vegetables": "सांगली-फळे भाजीपाला",
    "sangola": "सांगोला",
    "sakri": "साक्री",
    "satara": "सातारा",
    "savner": "सावनेर",
    "savli": "सावली",
    "sindkhed raja": "सिंधखेड राजा",
    "sindi selu": "सिंदी (सेलू)",
    "sindevahi": "सिंदेवाही",
    "sinnar": "सिन्नर",
    "sinnar naygav": "सिन्नर - नायगाव",
    "sinnar hivargaon": "सिन्नर - हिवरगांव",
    "arvi": "आर्वी",
    "indapur nimgaon ketki": "इंदापूर-निमगाव केतकी",
    "islampur": "इस्लामपूर",
    "umarkhed": "उमरखेड",
    "umarkhed danki": "उमरखेड-डांकी",
    "umarga": "उमरगा",
    "umarane": "उमराणे",
    "umari": "उमरी",
    "umred": "उमरेड",
    "ulhasnagar": "उल्हासनगर",
    "orad shahajani": "औराद शहाजानी",
    "ausa": "औसा",
    "kond": "कन्ड",
    "karmala": "करमाळा",
    "karad": "कराड",
    "karjat ahmednagar": "कर्जत (अहमहदनगर)",
    "karjat raigad": "कर्जत (रायगड)",
    "karjat rashin": "कर्जत- (राशिन)",
    "kalyan": "कल्याण",
    "kalamb dharashiv": "कळंब (धाराशिव)",
    "kalmeshwar": "कळमेश्वर",
    "kalvan": "कळवण",
    "katol": "काटोल",
    "kamthi": "कामठी",
    "karanja": "कारंजा",
    "kille dharur": "किल्ले धारुर",
    "kurdwadi": "कुर्डवाडी",
    "kurdwadi modnimb": "कुर्डवाडी-मोडनिंब",
    "kej": "केज",
    "kopargaon": "कोपरगाव",
    "koregaon": "कोरेगाव",
    "kolhapur": "कोल्हापूर",
    "khamgaon": "खामगाव",
    "khed": "खेड",
    "khed chakhan": "खेड-चाकण",
    "gangakhed": "गंगाखेड",
    "gangapur": "गंगापूर",
    "gadchiroli": "गडचिरोली",
    "gevenai": "गेवराई",
    "gondpimpiri": "गोंडपिंपरी",
    "gondia": "गोंदिया",
    "chandrapur ganjwad": "चंद्रपूर - गंजवड",
    "chandvad": "चांदवड",
    "chandur bazar": "चांदूर बझार",
    "chakur": "चाकूर",
    "charmoshi": "चार्मोशी",
    "chalisgav": "चाळीसगाव",
    "chalisgav nagdarod": "चाळीसगाव-नागदरोड",
    "chikhali": "चिखली",
    "chimur": "चिमुर",
    "chopda": "चोपडा",
    "chhatrapati sambhajinagar": "छत्रपती संभाजीनगर",
    "jalkot": "जळकोट",
    "jalgaon": "जळगाव",
    "jalgaon masavat": "जळगाव - मसावत",
    "jalgaon jamod asalgav": "जळगाव जामोद -असलगाव",
    "jafrabad": "जाफराबाद",
    "jamkhed": "जामखेड",
    "jalna": "जालना",
    "junnar": "जुन्नर",
    "junnar narayangav": "जुन्नर - नारायणगाव",
    "junnar aalfata": "जुन्नर-आळेफाटा",
    "junnar otur": "जुन्नर-ओतूर",
    "tasgav": "तासगाव",
    "tiroda": "तिरोडा",
    "tumsar": "तुमसर",
    "tuljapur": "तुळजापूर",
    "telhara": "तेल्हारा",
    "daryapur": "दर्यापूर",
    "dindori": "दिंडोरी",
    "dindori vani": "दिंडोरी-वणी",
    "digras": "दिग्रस",
    "dudhni": "दुधणी",
    "deulgaon raja": "देउळगाव राजा",
    "deoglur": "देगलूर",
    "devni": "देवणी",
    "devla": "देवळा",
    "dondaicha": "दोंडाईचा",
    "dondaicha sindkhed": "दोंडाईचा - सिंदखेड",
    "daund": "दौंड",
    "daund kedgav": "दौंड-केडगाव",
    "daund patas": "दौंड-पाटस",
    "dhadgav": "धडगाव",
    "dharangav": "धरणगाव",
    "dhamangav railway": "धामणगाव - रेल्वे",
    "dharashiv": "धाराशिव",
    "dhule": "धुळे",
    "nandurbar": "नंदूरबार",
    "nandgaon": "नांदगाव",
    "nandura": "नांदूरा",
    "nanded": "नांदेड",
    "nagpur": "नागपूर",
    "nagbhid": "नागभिड",
    "nampur": "नामपूर",
    "nampur karanjad": "नामपूर- करंजाड",
    "nashik": "नाशिक",
    "nashik devalali": "नाशिक - देवळाली",
    "ner parasopant": "नेर परसोपंत",
    "nevasa ghodegaon": "नेवासा -घोडेगाव",
    "pandharpur": "पंढरपूर",
    "panvel": "पनवेल",
    "paratour": "परतूर",
    "parbhani": "परभणी",
    "parli vaijnath": "परळी-वैजनाथ",
    "paranda": "परांडा",
    "palus": "पलूस",
    "pachora": "पाचोरा",
    "patan": "पाटन",
    "patur": "पातूर",
    "pathardi": "पाथर्डी",
    "parner": "पारनेर",
    "parshivani": "पारशिवनी",
    "parola": "पारोळा",
    "palghar bevur": "पालघर (बेवूर)",
    "pimpalgaon baswant": "पिंपळगाव बसवंत",
    "pimpalgaon palkhed": "पिंपळगाव (ब) - पालखेड",
    "pimpalgaon saykheda": "पिंपळगाव (ब) - सायखेडा",
    "pune": "पुणे",
    "pune khadki": "पुणे-खडकी",
    "pune pimpri": "पुणे-पिंपरी",
    "pune manjari": "पुणे-मांजरी",
    "pune moshi": "पुणे-मोशी",
    "pen": "पेन",
    "paithan": "पैठण",
    "pombhurni": "पोम्भुर्नी",
    "faltan": "फलटण",
    "babhulgaon": "बाभुळगाव",
    "baramati": " बारामती",
    "baramati jalochi": "बारामती-जळोची",
    "barshi": "बार्शी",
    "barshi vairag": "बार्शी-वैराग",
    "balapur": "बाळापूर",
    "bid": "बीड",
    "buldhana": "बुलढाणा",
    "bramhpuri": "ब्रम्हपूरी",
    "bhandara": "भंडारा",
    "bhivandi": "भिवंडी",
    "bhivapur": "भिवापूर",
    "bhusaval": "भुसावळ",
    "bhokar": "भोकर",
    "bhokardan": "भोकरदन",
    "bhokardan piplgav renu": "भोकरदन-पिपळगाव रेणू",
    "bhor": "भोर",
    "mangrulpir": "मंगरुळपीर",
    "mangalweda": "मंगळवेढा",
    "manglur pir shelubazar": "मंगळूरपीर - शेलूबाजार",
    "manchar": "मंचर",
    "manchar vani": "मंचर-वणी",
    "manmad": "मनमाड",
    "malkapur": "मलकापूर",
    "majalgav": "माजलगाव",
    "mangaon bhadav": "मानगाव (भादव)",
    "manora": "मानोरा",
    "malegaon": "मालेगाव",
    "malegaon mungse": "मालेगाव-मुंगसे",
    "mumbai": "मुंबई",
    "mumbai kanda batata market": "मुंबई - कांदा बटाटा मार्केट",
    "mumbai fruit market": "मुंबई - फ्रुट मार्केट",
    "mukhed": "मुखेड",
    "mukhed mukramabad": "मुखेड (मुक्रमाबाद)",
    "mudkhed": "मुदखेड",
    "murbad": "मुरबाड",
    "murud": "मुरुड",
    "morum": "मुरुम",
    "murtijapur": "मुर्तीजापूर",
    "mul": "मुल",
    "mehkar": "मेहकर",
    "motala": "मोताळा",
    "morshi": "मोर्शी",
    "mohol": "मोहोळ",
    "yavatmal": "यवतमाळ",
    "yewla": "येवला",
    "yevla andarsul": "येवला-आंदरसूल",
    "sinnar nandur shingote": "सिन्नर- नांदूर शिंगोटे",
    "sillod": "सिल्लोड",
    "sillod bharadi": "सिल्लोड- भराडी",
    "sengav": "सेनगाव",
    "solapur": "सोलापूर",
    "hinganghat": "हिंगणघाट",
    "hinga": "हिंगणा",
    "hingoli": "हिंगोली",
    "hingoli khanegaon naka": "हिंगोली- खानेगाव नाका",
    "vadgav peth": "वडगाव पेठ",
    "vadvani": "वडवणी",
    "vaduj": "वडूज",
    "vani": "वणी",
    "varud rajura bazar": "वरूड-राजूरा बझार",
    "varora shegav": "वरोरा-शेगाव",
    "wardha": "वर्धा",
    "vasai": "वसई",
    "vai": "वाई",
    "vashi dharashiv": "वाशी (धाराशिव)",
    "vashim": "वाशीम",
    "vashim anseeng": "वाशीम - अनसींग",
    "vita": "विटा",
    "vaijapur": "वैजापूर",
    "vaijapur shiur": "वैजापूर- शिऊर",
    "shahada": "शहादा",
    "shirpur": "शिरपूर",
    "shirur": "शिरुर",
    "shirur kanda market": "शिरुर-कांदा मार्केट",
    "shegav": "शेगाव",
    "ratnagiri": "रत्नागिरी",
    "ramtek": "रामटेक",
    "raver": "रावेर",
    "rahta": "राहता",
    "rahuri": "राहुरी",
    "rahuri wambori": "राहुरी-वांबोरी",
    "risod": "रिसोड",
    "roha": "रोहा",
    "lakhani": "लाखणी",
    "latur": "लातूर",
    "latur murud": "लातूर-मुरुड",
    "lasalgaon": "लासलगाव",
    "lasalgaon nifad": "लासलगाव - निफाड",
    "lasalgaon vinchur": "लासलगाव - विंचूर",
    "lasur station": "लासूर स्टेशन",
    "lonand": "लोणंद",
    "lonar": "लोणार",
    "loha": "लोहा",
    "tatygat gor": "तत्यगात गोर"
}

def fetch_msamb_by_crop(crop_mr):
    driver = webdriver.Chrome()
    driver.get("https://www.msamb.com/ApmcDetail/APMCPriceInformation")
    time.sleep(3)
    select_elem = Select(driver.find_element(By.ID, "drpCommodities"))
    select_elem.select_by_visible_text(crop_mr)
    time.sleep(3)
    rows = driver.find_elements(By.CSS_SELECTOR, "table tr")
    data = []
    for row in rows:
        cols = [col.text for col in row.find_elements(By.TAG_NAME, "td")]
        if cols:
            data.append(cols)
    header = [th.text for th in rows[0].find_elements(By.TAG_NAME, "th")]
    df = pd.DataFrame(data, columns=header)
    print(f"Market data for crop '{crop_mr}' fetched successfully.")
    driver.quit()
    return df

def get_rates_for_city(df, city_en):
    city_mr = city_en_to_mr.get(city_en.lower())
    if not city_mr:
        print(f"City '{city_en}' not found in translation dictionary.")
        return
    filtered = df[df['बाजार समिती'].str.contains(city_mr, na=False)]
    if filtered.empty:
        print(f"No market data found for city '{city_en}' ({city_mr}).")
        return
    filtered = filtered.copy()
    filtered['City (English)'] = city_en.capitalize()
    print(f"Market rates for crop in city '{city_en}':")
    print(filtered.to_string(index=False))

def main():
    crop_en = input("Enter crop name (English): ").strip().lower()
    city_en = input("Enter city name (English): ").strip().lower()
    crop_mr = crop_en_to_mr.get(crop_en)
    if not crop_mr:
        print(f"Crop '{crop_en}' not found in translation dictionary.")
        return
    df = fetch_msamb_by_crop(crop_mr)
    get_rates_for_city(df, city_en)

if __name__ == "__main__":
    main()
